version: '3.8'

services:
  # -----------------------------------------------------------
  # 1. NODE VỆ TINH 1 (SAT_001)
  # -----------------------------------------------------------
  sat_node_01:
    build: 
      context: .. 
      dockerfile: docker-config/Dockerfile 
    platform: linux/arm64
    container_name: GS_LONDON
    hostname: sat_node_01 # Đổi hostname thành tên service viết thường cho Service Discovery
    command: ["java", "-Duser.language=en", "-Duser.country=US", "-jar", "app.jar",
              "GS_LONDON"] # CHỈ CẦN NODE ID. Port được lấy từ DB/mặc định.
    ports:
      - "8001:8001" 
    restart: on-failure
    networks:
      - sagin_network

  # -----------------------------------------------------------
  # 2. NODE VỆ TINH 2 (SAT_002)
  # -----------------------------------------------------------
  sat_node_02:
    build: 
      context: .. 
      dockerfile: docker-config/Dockerfile 
    platform: linux/arm64
    container_name: SAT_002
    hostname: sat_node_02
    command: ["java", "-Duser.language=en", "-Duser.country=US", "-jar", "app.jar",
              "SAT_002"]
    ports:
      - "7001:7001"
    restart: on-failure
    networks:
      - sagin_network

  # -----------------------------------------------------------
  # 3. NODE TRẠM MẶT ĐẤT 1 (GS_001)
  # -----------------------------------------------------------
  gs_node_01:
    build: 
      context: ..
      dockerfile: docker-config/Dockerfile
    platform: linux/arm64
    container_name: GS_001
    hostname: gs_node_01
    command: ["java", "-Duser.language=en", "-Duser.country=US", "-jar", "app.jar",
              "GS_001"]
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - sagin_network

  # -----------------------------------------------------------
  # 4. NODE TRẠM MẶT ĐẤT 2 (GS_002)
  # -----------------------------------------------------------
  gs_node_02:
    build: 
      context: ..
      dockerfile: docker-config/Dockerfile
    platform: linux/arm64
    container_name: GS_002
    hostname: gs_node_02
    command: ["java", "-Duser.language=en", "-Duser.country=US", "-jar", "app.jar",
              "GS_002"]
    ports:
      - "5002:5002"
    restart: on-failure
    networks:
      - sagin_network
  
  # -----------------------------------------------------------
  # 5. NODE UAV (UAV_001)
  # -----------------------------------------------------------
  uav_node_01:
    build: 
      context: ..
      dockerfile: docker-config/Dockerfile
    platform: linux/arm64
    container_name: UAV_001
    hostname: uav_node_01
    command: ["java", "-Duser.language=en", "-Duser.country=US", "-jar", "app.jar",
              "UAV_001"]
    ports:
      - "4001:4001"
    restart: on-failure
    networks:
      - sagin_network

  # -----------------------------------------------------------
  # 6. NODE TÀU BIỂN (SEA_001)
  # -----------------------------------------------------------
  sea_node_01:
    build: 
      context: ..
      dockerfile: docker-config/Dockerfile
    platform: linux/arm64
    container_name: SEA_001
    hostname: sea_node_01
    command: ["java", "-Duser.language=en", "-Duser.country=US", "-jar", "app.jar",
              "SEA_001"]
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      - sagin_network

# -----------------------------------------------------------
# ĐỊNH NGHĨA MẠNG LƯỚI
# -----------------------------------------------------------
networks:
  sagin_network:
    driver: bridge