name: CI Test

on:
  pull_request:
    branches: 
      - develop
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Make test script executable
        run: chmod +x scripts/test.sh

      - name: Run test script
        run: ./scripts/test.sh
